services:

  python_project_debianizer: # handles -march= / -mtune= architecture-specific distribution
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_project_debianizer
    restart: unless-stopped
    hostname: python_project_debianizer.innovanon.com
    environment:
      - VIRTUAL_HOST=python_project_debianizer.innovanon.com
      - VIRTUAL_PORT=9322
#      - PROFILE_DIR=/var/lib/chimera/profiles
    volumes:
      - python_project_cloner-repos:/mnt/shared
#    depends_on:
#      - ssl-companion

#volumes:
#  python_project_cloner-repos


